# Buildpacks to include in builder
[[buildpacks]]
uri = "."

[[order]]
    [[order.group]]
    id = "ghcr.io/codbex/kronos-buildpacks-kyma-runtime"
    version = "#{KronosVersion}#"

[stack]
id = "com.codbex.kronos"
build-image = "ghcr.io/codbex/kronos-buildpacks-stack-build-kyma-runtime"
run-image = "ghcr.io/codbex/kronos-buildpacks-stack-run-kyma-runtime"
