# Buildpack API version
api = "0.5"

# Buildpack ID and metadata
[buildpack]
id = "ghcr.io/codbex/kronos-buildpacks"
version = "#{KronosVersion}#"
name = "Kronos Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "com.codbex.kronos"
